#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main(){
    srand(time(NULL));
    int a=rand()%1000;

  
    printf("a=%d\n",a);

    printf("rand = %d\n",rand());
    return 0;
}

/*
        NOTES:
    rand() generates a pseudo-random number
    srand() seeds the random number generator with a starting point

    basically, without srand(time(NULL)), the rand() function will produce the same sequence of numbers each time you run the program.
    Using srand(time(NULL)) ensures that the random numbers generated by rand() are different each time you run the program, as it uses the current time as a seed.
*/